import type { QuoteRecord } from "./quote.types";

export const mockQuotes: QuoteRecord[] = [
  {
    id: "QT-1024",
    client: "Inmobiliaria Delta",
    phone: "+56 9 8765 4321",
    service: "Portón industrial",
    city: "Santiago",
    status: "Pendiente",
    priority: "Alta",
    date: "2026-07-03",
    amount: 4900,
    description: "Solicitud para acceso principal de proyecto inmobiliario con estructura reforzada y seguridad premium.",
    measures: "4.20m x 2.80m · 2 hojas",
    material: "Acero galvanizado + pintura industrial",
    photos: ["Mock photo 1", "Mock photo 2", "Mock photo 3"],
    history: ["Solicitud recibida", "Revisión técnica pendiente", "Contacto con cliente programado"],
    timeline: [
      { label: "Cotización creada", time: "09:30", status: "Pendiente" },
      { label: "Cliente contactado", time: "11:15", status: "Contactado" },
    ],
    notes: "Requiere visita técnica para confirmar medidas exactas.",
  },
  {
    id: "QT-1025",
    client: "MetalWorks Plaza",
    phone: "+56 9 8123 9012",
    service: "Estructura metálica",
    city: "Rancagua",
    status: "Contactado",
    priority: "Media",
    date: "2026-07-04",
    amount: 7250,
    description: "Proyecto de soporte para instalación de cubierta metálica con requerimientos de montaje rápido.",
    measures: "6.50m x 3.10m · estructura compuesta",
    material: "Perfil estructural y lámina perfilada",
    photos: ["Mock photo 4", "Mock photo 5"],
    history: ["Se confirmó reunión", "Se envió propuesta preliminar"],
    timeline: [
      { label: "Contacto realizado", time: "10:00", status: "Contactado" },
      { label: "Revisión técnica", time: "14:20", status: "En proceso" },
    ],
    notes: "Necesita aprobación de planimetría antes de avanzar.",
  },
  {
    id: "QT-1026",
    client: "Grupo Rivas",
    phone: "+56 9 7788 1100",
    service: "Baranda y escalera",
    city: "Concepción",
    status: "En proceso",
    priority: "Alta",
    date: "2026-07-05",
    amount: 5600,
    description: "Baranda para acceso exterior en residencia nueva y escalera metálica para patio interior.",
    measures: "5.20m x 1.80m · 2 niveles",
    material: "Tubular y acero inoxidable",
    photos: ["Mock photo 6"],
    history: ["Proyecto validado", "Material solicitado"],
    timeline: [
      { label: "Aprobación inicial", time: "08:40", status: "Aprobado" },
      { label: "Fabricación", time: "16:00", status: "En proceso" },
    ],
    notes: "Las medidas necesitan revisión final con el cliente.",
  },
  {
    id: "QT-1027",
    client: "Aceros Norte",
    phone: "+56 9 7210 3005",
    service: "Reparación estructural",
    city: "Temuco",
    status: "Aprobado",
    priority: "Baja",
    date: "2026-07-06",
    amount: 3180,
    description: "Revisión y reforzamiento de estructura existente para mejora de estabilidad.",
    measures: "2.80m x 1.40m · soporte puntual",
    material: "Perfil reforzado y soldadura",
    photos: ["Mock photo 7", "Mock photo 8"],
    history: ["Cotización aprobada", "Kit de materiales reservado"],
    timeline: [
      { label: "Aprobación recibida", time: "12:10", status: "Aprobado" },
      { label: "Instalación programada", time: "18:30", status: "Instalado" },
    ],
    notes: "El cliente confirmó avance con priorización de obra.",
  },
  {
    id: "QT-1028",
    client: "Viviendas San José",
    phone: "+56 9 6544 2108",
    service: "Portón residencial",
    city: "Viña del Mar",
    status: "Rechazado",
    priority: "Media",
    date: "2026-07-07",
    amount: 2600,
    description: "Portón de acceso en vivienda nueva con sistema manual y diseño minimalista.",
    measures: "3.00m x 2.10m · 1 hoja",
    material: "Lámina texturada y estructura liviana",
    photos: ["Mock photo 9"],
    history: ["Solicitud descartada por presupuesto"],
    timeline: [
      { label: "Cotización enviada", time: "13:50", status: "Pendiente" },
      { label: "Cliente rechazó propuesta", time: "15:05", status: "Rechazado" },
    ],
    notes: "El cliente indicó que preferirá un proveedor local.",
  },
  {
    id: "QT-1029",
    client: "Nexa Logistics",
    phone: "+56 9 7001 4040",
    service: "Malla de seguridad",
    city: "Talca",
    status: "Instalado",
    priority: "Alta",
    date: "2026-07-08",
    amount: 8900,
    description: "Instalación de malla de seguridad para perímetro de bodega logística.",
    measures: "10.00m x 6.00m · perímetro exterior",
    material: "Malla galvanizada y postes metálicos",
    photos: ["Mock photo 10", "Mock photo 11"],
    history: ["Se cerró instalación", "Seguimiento postventa activo"],
    timeline: [
      { label: "Instalación finalizada", time: "09:00", status: "Instalado" },
    ],
    notes: "Requiere inspección final en 7 días.",
  },
  {
    id: "QT-1030",
    client: "Constructora Aurora",
    phone: "+56 9 8833 7722",
    service: "Andamios y soporte",
    city: "Los Ángeles",
    status: "Pendiente",
    priority: "Alta",
    date: "2026-07-09",
    amount: 6100,
    description: "Solicitud de soporte temporal para obra de construcción con dos etapas pendientes.",
    measures: "8.40m x 4.50m · elevación parcial",
    material: "Perfil metálico y accesorios de anclaje",
    photos: ["Mock photo 12"],
    history: ["Se programó reunión de medición"],
    timeline: [
      { label: "Cotización registrada", time: "11:55", status: "Pendiente" },
    ],
    notes: "Necesita confirmar coordinación de logística y tiempos de montaje.",
  },
];
